name: example
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  shelf_router_classes:
    path: ../

dev_dependencies:
  lints: ^1.0.0
