name: shelf_router_classes
description: An easier way to declare and use routes for the shelf and shelf_router packages using classes and Route annotations.
version: 1.0.1
repository: https://github.com/dbilgin/shelf_router_classes

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  shelf_router: ^1.1.2

dev_dependencies:
  test: ^1.20.2
  lints: ^1.0.0
  shelf: ^1.3.0
