name: Testing

on: push


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dart-lang/setup-dart@v1
    - name: Install dependencies
      run: dart pub get

    - run: dart analyze .
    - run: dart test
